name: QA Automation

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar testes API
        run: pytest api_tests

      - name: Rodar testes WEB
        run: pytest web_tests